spring:
  application:
    name: eureka-server
  kafka:
    bootstrap-servers:
      - localhost:9092
server:
  port: 8765
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
kafka-topics:
  input: 'InTopic'
  output: 'OutTopic'
