version: '3.9'

services:
  postgres:
    image: postgres:15-alpine
    container_name: 'db'
    ports:
      - '5432:5432'
    environment:
      POSTGRES_DB: db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - './database-initialization:/docker-entrypoint-initdb.d'
