server:
  port: 24110
spring:
  jpa:
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: validate
  datasource:
    url: 'jdbc:postgresql://localhost:5432/db'
    username: 'postgres'
    password: 'postgres'
    driver-class-name: 'org.postgresql.Driver'
  liquibase:
    change-log: 'liquibase/changelog-master.xml'
    liquibase-schema: 'liquibase_schema'
    default-schema: 'distcomp'
