server:
  port: 24130
spring:
  cassandra:
    local-datacenter: datacenter1
    schema-action: create_if_not_exists
    keyspace-name: distcomp
    username: cassandra
    password: cassandra
    contact-points: 127.0.0.1
    port: 9042
  jpa:
    generate-ddl: true
